name: Deploy to GitHub Pages

on:
  # Ejecutar en push a la rama main
  push:
    branches: [ main ]
  # Permitir ejecución manual
  workflow_dispatch:

# Permisos necesarios para GitHub Pages
permissions:
  contents: read
  pages: write
  id-token: write

# Permitir solo un despliegue concurrente
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          cd barriofino_web
          npm ci

      - name: Build with Astro
        run: |
          cd barriofino_web
          npm run build

      - name: Upload artifact for deployment
        uses: actions/upload-pages-artifact@v3
        with:
          path: barriofino_web/dist

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
